version: '3'
services:
  wcontrol-api:
    container_name: wcontrol-api
    build:
      dockerfile: dockerfile
      context: .
    environment:
      - PREDICTION_PORT=5100
    ports:
      - '5012:5100'
    volumes:
      - /home/diego/wcontrol:/opt/wcontrol
      - /home/diego/wcontrol/experiments/experimentoZP1/pmodel:/opt/modelo-wc/pmodel
      - /home/diego/wcontrol/experiments/experimentoZP1/zmodel:/opt/modelo-wc/zmodel
